---
title: "Network Visualization"
format:
  html:
    page-layout: full
    embed-resources: true
editor: source
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

[networkD3](https://christophergandrud.github.io/networkD3/)     
[Network Analysis and Visualization with R and igraph](https://kateto.net/netscix2016.html)       
[Introduction to Network Analysis Using R](https://yunranchen.github.io/intro-net-r/index.html)        

```{r}
library(networkD3)
library(igraph)
```

# Force Network

```{r}
DF <- openxlsx::read.xlsx("pillars.xlsx")

head(DF)

DivNodes <- data.frame(name = union(DF$src, DF$target))
DivLinks <- data.frame(source = match(DF$src, DivNodes$name) - 1, 
                       target = match(DF$target, DivNodes$name) - 1)

DivNodes$group <- c(1:6, rep(7,21))
DivNodes$size <- rep(c(100,10), c(6,21))

# Create force Network
fn <- forceNetwork(Links = DivLinks, Nodes = DivNodes, Source = 'source',
                   Target = 'target', NodeID = 'name', Group = 'group', 
                   Nodesize = 'size', zoom = TRUE, linkDistance = 200,
                   width = 1200, height = 800)

# Where to find nodes data.frame
str(fn$x$nodes)

# Add hyperlinks to node data.frame  
fn$x$nodes$hyperlink <- c("https://med.nyu.edu/departments-institutes/population-health/divisions-sections-centers/biostatistics/",
                          "https://med.nyu.edu/departments-institutes/population-health/divisions-sections-centers/biostatistics/",
                          "https://med.nyu.edu/departments-institutes/population-health/divisions-sections-centers/biostatistics/",
                          "https://med.nyu.edu/departments-institutes/population-health/divisions-sections-centers/biostatistics/",
                          "https://med.nyu.edu/departments-institutes/population-health/divisions-sections-centers/biostatistics/",
                          "https://med.nyu.edu/departments-institutes/population-health/divisions-sections-centers/biostatistics/",
                          "https://med.nyu.edu/faculty/ivan-l-diaz",
                          "https://med.nyu.edu/faculty/michele-santacatterina",
                          "https://med.nyu.edu/faculty/nicholas-illenberger",
                          "https://med.nyu.edu/faculty/wenbo-wu",
                          "https://med.nyu.edu/faculty/samrachana-adhikari",
                          "https://med.nyu.edu/faculty/keith-s-goldfeld",
                          "https://med.nyu.edu/faculty/erinn-m-hade",
                          "https://med.nyu.edu/faculty/andrea-b-troxel",
                          "https://med.nyu.edu/faculty/cheongeun-oh",
                          "https://med.nyu.edu/faculty/chang-yu",
                          "https://med.nyu.edu/faculty/hayley-belli",
                          "https://med.nyu.edu/faculty/yongzhao-shao",
                          "https://med.nyu.edu/faculty/thaddeus-tarpey",
                          "https://med.nyu.edu/faculty/charles-cleland",
                          "https://med.nyu.edu/faculty/jiyuan-hu",
                          "https://med.nyu.edu/faculty/rebecca-anthopolos",
                          "https://med.nyu.edu/faculty/huilin-li",
                          "https://med.nyu.edu/faculty/judith-d-goldberg",
                          "https://med.nyu.edu/faculty/mengling-liu",
                          "https://med.nyu.edu/faculty/hyung-g-park",
                          "https://med.nyu.edu/faculty/hakhamanesh-mostafavi")

# define a click action to open the hyperlink for each node in a new window
fn$x$options$clickAction = 'window.open(d.hyperlink)'
```

## Click on a node to open a webpage
```{r}
fn
```



